### ISSUE TITLE
Data from bins as well as PM2.5 data 

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#32]
If I understand correctly, the units log the data from a number of size bins as well as the "PM" data e.g. PM2.5, but I'm not sure what happens to this data?  Would it be possible to get the code to write all this information in the same file?  So have the bins simply as columns in a .csv (or .db) file.  

Unless there is a reason it is done differently, in which case @wolfiex could you  explain? Thanks,

**Comment by wolfiex** [comment]
The histogram is currently saved as a pickle object. This can be expanded with `pickle.load` or `loads` when we decode the positional data when needed. This may be changed at a later point as long as the provided number of bins remains constant (I think it should). 

However, I find it much easier to get a list with all the bins when accessing the bins column, than having to select each individual one at a time. I presume the general usage will look at all bins as a unit, rather than individual ones? Am I correct in this assumption.

**Comment by cemac-ccs** [comment]
This has been made consistent along all three main branches (ie use of pickle)

**Comment by wolfiex** [comment]
It is worth noting that databases created prior to this change (ie for the first test period) do not contain individual bins.

**Comment by cemac-ccs** [comment]
Closing this issue as it has been dealt with and all active RPis should now be using the newer structured databases
