### ISSUE TITLE
sensorpi code fails when writing to db if old one with different columns exist 

### ISSUE THREAD

**Issue by KirstyPringle** [cemac/BBSensor#42]
Dan told me to do:

python3 -m sensorpi.SensorMod.db

Could this be automated?  Maybe move rather than delete (to be safe!)

**Comment by wolfiex** [comment]
@cemac-ccs  So empty dbs get created following successful upload.

**Comment by cemac-ccs** [comment]
In the short term, doing a manual copy to a separate folder prior to recreating the db will be best.

Do we forsee changes to the db structure in the future?

Currently the copying process works by copying the records themselves into a blank db and then dropping tables and recreating them. This means that new dbs are created on a successful upload. 

We could instead close the db connection, move the file and then create a new db file it its place, then return a success flag and the new connection as a tuple from the upload function. This will however still not catch the error caused by a new expected db structure while a db with the old structure still exists. 

What kind of exception is raised when it can't write to the db? We could put a try/except in and do a db copy/recreate process on exception maybe

**Comment by wolfiex** [comment]
I guess this should no longer be updated once all pis are updated. We can probably get paul to create a new image that everyone will use afterwards (he should have installed the RTC code, and thus will be most up to date)
